# Integrantes: Diego Henríquez y Diego Morales
# Asignatura: Ciberseguridad en Desarrollo
# Sección: OCY1102

global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'flask_app'
    static_configs:
      - targets: ['vulnerable-app-container:5000']